language: rust
rust:
  # For now, Ruse is nightly-only. I'd like to fix this in the long term,
  # but it's how things are for now.
  #
  #- stable
  #- beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
cache: cargo
script:
    - cd ruse && cargo build --verbose
    - cd ruse && cargo test --verbose
