[package]
name        = "libruse"
version     = "0.1.0"
authors     = ["Andrew Brinker <me@andrewbrinker.com>"]

[dependencies]
libruse-read = { path = "../libruse-read" }
libruse-eval = { path = "../libruse-eval" }
libruse-print = { path = "../libruse-print" }

